### PR TITLE
Add support for out of tree platforms

### LINKED ISSUE #1: Support for RN macOS
hi @oblador ! Thanks a lot for all your OSS contributions, this is yet another great package. I'm trying to integrate this with [Sol](https://github.com/ospfranco/sol), I think tree-shaking could make a big difference in performance, yet I'm facing some issues:

Screenshot 000532

I assume this has something to do with how rn-macos patches the base imports for the macOS platform. Any idea if this is possible to easily fix?

Thanks a lot!

### PR DESCRIPTION
**Pull request by oblador**
Fixes #1

### CODE REVIEW

**Comment by oblador** [comment]
@ospfranco would you mind helping me validate this PR with your project?

**Comment by ospfranco** [comment]
Will gladly do! although I need to find some time, maybe until the weekend :)

**Comment by oblador** [comment]
@ospfranco Found any time, if not I'll go ahead and merge.

**Comment by ospfranco** [comment]
no 🙈 really sorry, feel free to go ahead and merge :) I'll test later

**Pull request merged**
