### PR TITLE
Fix assetRegistryPath default value

### PR DESCRIPTION
**Pull request by Jinho1011**
This fixes issue #30 to support the latest version of react-native (0.72.1)

### CODE REVIEW

**Comment by oblador** [comment]
Since this would break older versions, would you mind making it a config with a default instead of hard coded value?

**Comment by oblador** [comment]
Hi, thanks for the PR! Would you mind fixing the example project by either updating it to 0.72 (preferred) or changing the config to point to the old registry path? Also, perhaps mention in the README on how to configure it for older versions?

**Comment by Jinho1011** [comment]
Thank you for reviewing my PR and providing feedback. I have updated the example's react-native version to 0.72 and made the necessary changes accordingly. The example project is now aligned with the latest version.

**Comment by oblador** [comment]
Thanks! It seems not all steps of the upgrade was applied, see this guide for all of them: https://react-native-community.github.io/upgrade-helper/?from=0.71.6&to=0.72.1

**Comment by Jinho1011** [comment]
I applied the changes for 0.72.1. Thanks for your guidance!

**Comment by oblador** [comment]
Sorry if this is a bit annoying, but it seems we also need to update the node version, you can do that in two places in this file: https://github.com/oblador/react-native-esbuild/blob/master/.github/workflows/tests.yml#L35

**Comment by Jinho1011** [comment]
No problem at all 👍

**Comment by oblador** [comment]
Yay, tests are passing :-D

**Review by oblador — APPROVED** [review]

**Comment by vovkasm** [comment]
Oh my... it is not so easy configurable from react-native.config.js for older versions of RN, because some constants and defaults calculated in the [getEsbuildConfig](https://github.com/oblador/react-native-esbuild/blob/v0.6.0/src/esbuild-config.js#L81-L86) where default plugin instantiated 😢

**Comment by oblador** [comment]
@vovkasm Can't you keep using 0.5.0? Or is there something in 0.6.0 that you need?

**Comment by vovkasm** [comment]
> @vovkasm Can't you keep using 0.5.0? Or is there something in 0.6.0 that you need?

Yes, of course I can keep using 0.5.0, but after version 0.6.0 will be version 0.7.0 etc...
Actually I'm alredy fixed this with `path-packege`, it was easy than overriding plugin args in `react-native.config.js` :-)

**Comment by oblador** [comment]
Maybe by 0.7.0 you have upgraded RN 😁

**Pull request merged**
